/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class App {
    final Level VERBOSE = Level.forName("VERBOSE", 150);

    private static final Logger logger = LogManager.getLogger(App.class);

    public static void main(final String... args) {

        App app = new App();

        if (logger.isErrorEnabled())
            logger.error("esto es un error");
        logger.info("Entering application.");
        logger.debug("esto es debug Logging!");
        logger.log(app.VERBOSE, "a verbose message");

    }
}
